// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="assignment,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.000000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=0,HLS_VERSION=2019_2}" *)

module assignment (
        a1_V,
        a2_V,
        a3_V,
        a4_V,
        b1_V,
        b2_V,
        b3_V
);


output  [40:0] a1_V;
output  [40:0] a2_V;
output  [40:0] a3_V;
output  [40:0] a4_V;
output  [762:0] b1_V;
output  [762:0] b2_V;
output  [762:0] b3_V;

assign a1_V = 41'd2063;

assign a2_V = 41'd2063;

assign a3_V = 41'd2063;

assign a4_V = 41'd2063;

assign b1_V = 763'd19835148582765468633513017367;

assign b2_V = 763'd19835148582765468633513017367;

assign b3_V = 763'd19835148582765468633513017367;

endmodule //assignment
