// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _automatic_inlining_HH_
#define _automatic_inlining_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct automatic_inlining : public sc_module {
    // Port declarations 3
    sc_in< sc_logic > a;
    sc_in< sc_logic > b;
    sc_out< sc_logic > c;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    automatic_inlining(sc_module_name name);
    SC_HAS_PROCESS(automatic_inlining);

    ~automatic_inlining();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<1> > xor_ln6_fu_47_p0;
    sc_signal< sc_lv<1> > and_ln11_fu_53_p0;
    sc_signal< sc_lv<1> > xor_ln6_fu_47_p2;
    static const bool ap_const_boolean_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_and_ln11_fu_53_p0();
    void thread_c();
    void thread_xor_ln6_fu_47_p0();
    void thread_xor_ln6_fu_47_p2();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
