// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="test_vhls,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.766000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=17,HLS_VERSION=2019_2}" *)

module test_vhls (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sw_V,
        led_V,
        led_V_ap_vld
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] sw_V;
output  [7:0] led_V;
output   led_V_ap_vld;

reg led_V_ap_vld;

wire   [0:0] icmp_ln879_fu_33_p2;

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        led_V_ap_vld = 1'b1;
    end else begin
        led_V_ap_vld = 1'b0;
    end
end

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

assign icmp_ln879_fu_33_p2 = ((sw_V == 8'd15) ? 1'b1 : 1'b0);

assign led_V = ((icmp_ln879_fu_33_p2[0:0] === 1'b1) ? 8'd240 : 8'd1);

endmodule //test_vhls
