// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _test_vhls_HH_
#define _test_vhls_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct test_vhls : public sc_module {
    // Port declarations 7
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<8> > sw_V;
    sc_out< sc_lv<8> > led_V;
    sc_out< sc_logic > led_V_ap_vld;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    test_vhls(sc_module_name name);
    SC_HAS_PROCESS(test_vhls);

    ~test_vhls();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<1> > icmp_ln879_fu_33_p2;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<8> ap_const_lv8_F;
    static const sc_lv<8> ap_const_lv8_F0;
    static const sc_lv<8> ap_const_lv8_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_icmp_ln879_fu_33_p2();
    void thread_led_V();
    void thread_led_V_ap_vld();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
