// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "test_vhls.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic test_vhls::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic test_vhls::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> test_vhls::ap_const_lv8_F = "1111";
const sc_lv<8> test_vhls::ap_const_lv8_F0 = "11110000";
const sc_lv<8> test_vhls::ap_const_lv8_1 = "1";
const bool test_vhls::ap_const_boolean_1 = true;

test_vhls::test_vhls(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );

    SC_METHOD(thread_icmp_ln879_fu_33_p2);
    sensitive << ( ap_start );
    sensitive << ( sw_V );

    SC_METHOD(thread_led_V);
    sensitive << ( ap_start );
    sensitive << ( icmp_ln879_fu_33_p2 );

    SC_METHOD(thread_led_V_ap_vld);
    sensitive << ( ap_start );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_virtual_clock.pos() );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "test_vhls_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, sw_V, "(port)sw_V");
    sc_trace(mVcdFile, led_V, "(port)led_V");
    sc_trace(mVcdFile, led_V_ap_vld, "(port)led_V_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, icmp_ln879_fu_33_p2, "icmp_ln879_fu_33_p2");
#endif

    }
    mHdltvinHandle.open("test_vhls.hdltvin.dat");
    mHdltvoutHandle.open("test_vhls.hdltvout.dat");
}

test_vhls::~test_vhls() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void test_vhls::thread_ap_done() {
    ap_done = ap_start.read();
}

void test_vhls::thread_ap_idle() {
    ap_idle = ap_const_logic_1;
}

void test_vhls::thread_ap_ready() {
    ap_ready = ap_start.read();
}

void test_vhls::thread_icmp_ln879_fu_33_p2() {
    icmp_ln879_fu_33_p2 = (!sw_V.read().is_01() || !ap_const_lv8_F.is_01())? sc_lv<1>(): sc_lv<1>(sw_V.read() == ap_const_lv8_F);
}

void test_vhls::thread_led_V() {
    led_V = (!icmp_ln879_fu_33_p2.read()[0].is_01())? sc_lv<8>(): ((icmp_ln879_fu_33_p2.read()[0].to_bool())? ap_const_lv8_F0: ap_const_lv8_1);
}

void test_vhls::thread_led_V_ap_vld() {
    if (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) {
        led_V_ap_vld = ap_const_logic_1;
    } else {
        led_V_ap_vld = ap_const_logic_0;
    }
}

void test_vhls::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"sw_V\" :  \"" << sw_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"led_V\" :  \"" << led_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"led_V_ap_vld\" :  \"" << led_V_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

