// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _sw_control_led_HH_
#define _sw_control_led_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct sw_control_led : public sc_module {
    // Port declarations 2
    sc_in< sc_lv<8> > inputs;
    sc_out< sc_lv<8> > outputs;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    sw_control_led(sc_module_name name);
    SC_HAS_PROCESS(sw_control_led);

    ~sw_control_led();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    static const bool ap_const_boolean_1;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_outputs();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
