// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _basic_output_HH_
#define _basic_output_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct basic_output : public sc_module {
    // Port declarations 1
    sc_out< sc_lv<8> > o;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    basic_output(sc_module_name name);
    SC_HAS_PROCESS(basic_output);

    ~basic_output();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    static const sc_lv<8> ap_const_lv8_F0;
    static const bool ap_const_boolean_1;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_o();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
