// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "combinational_loop.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic combinational_loop::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<2> combinational_loop::ap_ST_fsm_state1 = "1";
const sc_lv<2> combinational_loop::ap_ST_fsm_state2 = "10";
const sc_lv<32> combinational_loop::ap_const_lv32_1 = "1";
const sc_lv<3> combinational_loop::ap_const_lv3_0 = "000";
const sc_lv<32> combinational_loop::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> combinational_loop::ap_const_lv1_0 = "0";
const sc_lv<3> combinational_loop::ap_const_lv3_5 = "101";
const sc_lv<3> combinational_loop::ap_const_lv3_1 = "1";
const sc_lv<1> combinational_loop::ap_const_lv1_1 = "1";
const sc_logic combinational_loop::ap_const_logic_0 = sc_dt::Log_0;
const bool combinational_loop::ap_const_boolean_1 = true;

combinational_loop::combinational_loop(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln700_fu_72_p2);
    sensitive << ( led_V_i );
    sensitive << ( zext_ln700_fu_68_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_i_fu_62_p2);
    sensitive << ( op2_assign_reg_45 );

    SC_METHOD(thread_icmp_ln7_fu_56_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( op2_assign_reg_45 );

    SC_METHOD(thread_led_V_o);
    sensitive << ( led_V_i );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln7_fu_56_p2 );
    sensitive << ( add_ln700_fu_72_p2 );

    SC_METHOD(thread_zext_ln700_fu_68_p1);
    sensitive << ( op2_assign_reg_45 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln7_fu_56_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "01";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "combinational_loop_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, led_V_i, "(port)led_V_i");
    sc_trace(mVcdFile, led_V_o, "(port)led_V_o");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, i_fu_62_p2, "i_fu_62_p2");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, op2_assign_reg_45, "op2_assign_reg_45");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, icmp_ln7_fu_56_p2, "icmp_ln7_fu_56_p2");
    sc_trace(mVcdFile, add_ln700_fu_72_p2, "add_ln700_fu_72_p2");
    sc_trace(mVcdFile, zext_ln700_fu_68_p1, "zext_ln700_fu_68_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("combinational_loop.hdltvin.dat");
    mHdltvoutHandle.open("combinational_loop.hdltvout.dat");
}

combinational_loop::~combinational_loop() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void combinational_loop::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln7_fu_56_p2.read(), ap_const_lv1_0))) {
        op2_assign_reg_45 = i_fu_62_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        op2_assign_reg_45 = ap_const_lv3_0;
    }
}

void combinational_loop::thread_add_ln700_fu_72_p2() {
    add_ln700_fu_72_p2 = (!led_V_i.read().is_01() || !zext_ln700_fu_68_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(led_V_i.read()) + sc_biguint<8>(zext_ln700_fu_68_p1.read()));
}

void combinational_loop::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void combinational_loop::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void combinational_loop::thread_i_fu_62_p2() {
    i_fu_62_p2 = (!op2_assign_reg_45.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(op2_assign_reg_45.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void combinational_loop::thread_icmp_ln7_fu_56_p2() {
    icmp_ln7_fu_56_p2 = (!op2_assign_reg_45.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(op2_assign_reg_45.read() == ap_const_lv3_5);
}

void combinational_loop::thread_led_V_o() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln7_fu_56_p2.read(), ap_const_lv1_0))) {
        led_V_o = add_ln700_fu_72_p2.read();
    } else {
        led_V_o = led_V_i.read();
    }
}

void combinational_loop::thread_zext_ln700_fu_68_p1() {
    zext_ln700_fu_68_p1 = esl_zext<8,3>(op2_assign_reg_45.read());
}

void combinational_loop::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln7_fu_56_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

void combinational_loop::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"led_V_i\" :  \"" << led_V_i.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"led_V_o\" :  \"" << led_V_o.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

